### ISSUE TITLE
Hogwarts Reklamcısı

### ISSUE THREAD

**Issue by ByPikod** [gInterpol/gInterpol#19]
### STEAM ID

76561199022922424

### Rapor sebebi
Reklam

### Kanıt
![img](https://cdn.discordapp.com/attachments/777474237127852042/801892246948675584/Screenshot_20210121-221321.png)
![img](https://cdn.discordapp.com/attachments/706977856550600745/801893919062491166/Capture.PNG)

**Comment by Sardonyx78** [comment]
Eğer başka sunucularda da yapıyorsa işlem yapılır bu arada discord IDsini atar mısın?

**Comment by hypheoN** [comment]
yapmauin olm adama bişey 😭
